version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    target-branch: "next-dev"
  - package-ecosystem: "cargo"
    directory: "/libs/asset-checksum"
    schedule:
      interval: "daily"
    target-branch: "next-dev"
