packageExtensions:
  react-materialize@*:
    dependencies:
      prop-types: ^15.8.1
  safe-buffer@*:
    dependencies:
      buffer: ^6.0.3
  sax@*:
    dependencies:
      string_decoder: ^1.3.0
  xml2js@*:
    dependencies:
      events: ^3.3.0
      timers: "npm:timers-browserify@^2.0.12"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
