yarnPath: .yarn/releases/yarn-3.2.4.cjs

packageExtensions:
  react-materialize@*:
    dependencies:
      "prop-types": "^15.8.1"

  safe-buffer@*:
    dependencies:
      "buffer": "^6.0.3"

  sax@*:
    dependencies:
      "string_decoder": "^1.3.0"

  xml2js@*:
    dependencies:
      "timers": "npm:timers-browserify@^2.0.12"
      "events": "^3.3.0"
