// Generated by get_precache_files.py
export const EXTRA_PRECACHE_FILES = [
	{ url: '/assets/recorder/encoderWorker.min.wasm', revision: '2018' },
	{ url: '/assets/recorder/decoderWorker.min.wasm', revision: '2018' },
];
