//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.01 at 08:59:17 PM NZDT 
//


package com.getmicropad.parser;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.getmicropad.parser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Notepad_QNAME = new QName("", "notepad");
    private final static QName _NoteTypeBibliographySource_QNAME = new QName("", "source");
    private final static QName _AddonsTypeImport_QNAME = new QName("", "import");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.getmicropad.parser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link NotepadType }
     * 
     */
    public NotepadType createNotepadType() {
        return new NotepadType();
    }

    /**
     * Create an instance of {@link MarkdownType }
     * 
     */
    public MarkdownType createMarkdownType() {
        return new MarkdownType();
    }

    /**
     * Create an instance of {@link DrawingType }
     * 
     */
    public DrawingType createDrawingType() {
        return new DrawingType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link RecordingType }
     * 
     */
    public RecordingType createRecordingType() {
        return new RecordingType();
    }

    /**
     * Create an instance of {@link AddonsType }
     * 
     */
    public AddonsType createAddonsType() {
        return new AddonsType();
    }

    /**
     * Create an instance of {@link BibliographyType }
     * 
     */
    public BibliographyType createBibliographyType() {
        return new BibliographyType();
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link NoteType.Bibliography }
     * 
     */
    public NoteType.Bibliography createNoteTypeBibliography() {
        return new NoteType.Bibliography();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotepadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "notepad")
    public JAXBElement<NotepadType> createNotepad(NotepadType value) {
        return new JAXBElement<NotepadType>(_Notepad_QNAME, NotepadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source", scope = NoteType.Bibliography.class)
    public JAXBElement<SourceType> createNoteTypeBibliographySource(SourceType value) {
        return new JAXBElement<SourceType>(_NoteTypeBibliographySource_QNAME, SourceType.class, NoteType.Bibliography.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "import", scope = AddonsType.class)
    public JAXBElement<String> createAddonsTypeImport(String value) {
        return new JAXBElement<String>(_AddonsTypeImport_QNAME, String.class, AddonsType.class, value);
    }

}
